### ISSUE TITLE
font not found (KDE Plasma X11)

### ISSUE THREAD

**Issue by 1fbw** [yoshisaac/CounterStrikeSource-Linux-Trainer#3]
i followed the guide, installed what i had to and when  i run it (after building/compiling it) it goes fully black, when i check the terminal it spams 
`font not found, aborting.`
and then
```
 X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x1
  Serial number of failed request:  2578987
  Current serial number in output stream:  2578987
font not found, aborting.
```
and completely stops

**Comment by 1fbw** [comment]
forgot to mention, im using arch

**Comment by yoshisaac** [comment]
Hello, thank you for making an Issue.

From my testing on Arch, it had worked fine for me after installing the font packaged I listed in the Read Me. I'd be happy to debug your issue further.

For the part about your screen going fully black: what window manager and or desktop environment do you use? Are you using X11 or Wayland? I have an Arch machine of my own that I'll test it on. I've only seen it work on the Cinnamon desktop, and a contributor of the project had it working on Dwm.

**Comment by yoshisaac** [comment]
I've been able to re-produce the black screen issue with Arch, on KDE Plasma X11. Although, on Wayland with the same desktop environment it works just fine. I guess Xwayland converts the calls better than what KDE Plasma has by default?

I most likely will not fix the problem any time soon on Plasma with X11, as that is not my preferred DE nor do I use X11 when I do. If you are using KDE, my suggestion to you is (if you want to continue using KDE Plasma,) switch to the Wayland session.

If this problem is happening on another desktop environment, then I'll be happy to test it when you tell me. Other than that, I'll close the issue once you give some sort of confirmation.

**Comment by yoshisaac** [comment]
For the missing font: You need to restart your computer for the changes to apply after installation on Arch Linux.
